debug: true

# MYSQL Database
username: root
database: pickmc
password: password
ip: localhost
port: 3306

# Shop Villager name
ShopVillagerName: "&a&lSHOP"

# No Permission Message
InvalidPermission: "&c&lERROR > &8You don't have permission to use this command."

# Explosion Perk (placeholder: %player%)
ExplosionChance: 30
ExplosionActivated: "&6&lPERK > &2Explosion Perk activated!"
ExplosionActivatedActionbar: ""
ExplosionDamage: "&6&lPERK > &cYou have been damaged by &4&l%player%&c's Explosion Perk!"
ExplosionDamageActionbar: ""

# Absorption Perk
AbsorptionChance: 35
AbsorptionDuration: 11
AbsorptionActivated: "&6&lPERK > &2Absorption Perk activated!"
AbsorptionActivatedActionbar: ""

# Speed Perk
SpeedChance: 100
SpeedDuration: 5
SpeedActivated: "&6&lPERK > &2Speed Perk activated!"
SpeedActivatedActionbar: ""

# Kick message when a players profile has failed to save
FailedProfileSave: "&cError saving your profile. If this consists please contact &c&lZxoir"

# Error message when selecting same kit
SameKitError: "&c&lERROR > &8You already have that Kit selected!"

# Error when a player leaves spawn without selecting a Kit
NoKitError: "&c&lERROR > &8You must select a Kit!"

# Error when a player tries to access a kit he doesn't have access to
NoKitAccessError: "&c&lERROR > &8You don't have access to that Kit!"

# Error when a player attempts to use the Kit command outside Spawn
KitOutsideSpawnError: "&c&lERROR > &8You can't use that here!"

# Message when you are killed (Placeholders: %killer% %killed% %points_removed%)
killed_message: "&cYou have been killed by %killer%"
killed_actionbar: "&c-%points_removed%"

# Message when you kill someone (Placeholders: %killer% %killed% %points_gained% %xp_gained%)
kill_message: "&aYou killed %killed%"
kill_actionbar: "&a+%points_gained% &9+%xp_gained%"

# Combatlog messages (Placeholders: %player_hit% %time%)
combat_countdown: true
combat_message: ""
combat_actionbar: "&c&lCOMBATLOG > &8You're in combat for %time% seconds!"
combatlog_kill_message: ""
combatlog_finish_message: "&c&lCOMBATLOG > &aYou're no longer in Combat!"
combat_time: 15

# Message when you level up (Placeholders: %player% %new_level% %old_level%)
levelUp_title: "&a&lYou have leveled up"
levelUp_subtitle: "&9%old_level% &8-> &9%new_level%"
levelUp_broadcast: "&a&l%player% &9has leveled up to &9&l%new_level%&9!"