debug: true

# MYSQL Database
username: root
database: pickmc
password: password
ip: localhost
port: 3306

XpBoosts:
  permission: 1.7
  pick: 1.5
  pickplus+: 1.7

CoinBoosts:
  permission: 1.7
  pick: 1.5
  pick+: 1.7

# Shop Villager name
ShopVillagerName: "&a&lSHOP"

# Fire Tick Speed (19 Seconds MAX)
FireTickSpeed: 2

# Vote Pending Message
VotePendingMessage: "&e&lThank you for voting! &eYou will receive your Reward once you're in &e&lSpawn&e!"

# Vote Received Message
VoteReceivedMessage: "&e&lThank you for voting! &eYour reward is in your inventory!"

# Vote Received Message While Offline
VoteReceivedOfflineMessage: "&eYou have received your voting rewards!"

# No Permission Message
InvalidPermission: "&c&lERROR > &8You don't have permission to use this command."

# Purchase Messages (Placeholders: %kit_name% %kit_price% %perk_name% %perk_price%)
KitPurchaseMessage: "&aYou have purchased &e&l%kit_name% &afor &e&l%kit_price%¢"
PerkPurchaseMessage: "&aYou have purchased &e&l%perk_name% &afor &e&l%perk_price%¢"

# Speed Kit
SpeedKitPrice: 2000
SpeedKitExpire: 86400
SpeedKitLevel: 5
SpeedKitEffectDuration: 6

# Strength Kit
StrengthKitPrice: 2500
StrengthKitExpire: 86400
StrengthKitLevel: 8

# Tank Kit
TankKitPrice: 1000
TankKitExpire: 86400
TankKitLevel: 3

# Explosion Perk (Placeholder: %player%)
ExplosionRadius: 5
ExplosionPrice: 100
ExplosionExpire: 86400
ExplosionLevel: 0
ExplosionChance: 30
ExplosionActivated: "&6&lPERK > &2Explosion Perk activated!"
ExplosionActivatedActionbar: ""
ExplosionDamage: "&6&lPERK > &cYou have been damaged by &4&l%player%&c's Explosion Perk!"
ExplosionDamageActionbar: ""

# Absorption Perk
AbsorptionPrice: 100
AbsorptionExpire: 86400
AbsorptionLevel: 0
AbsorptionChance: 35
AbsorptionDuration: 11
AbsorptionActivated: "&6&lPERK > &2Absorption Perk activated!"
AbsorptionActivatedActionbar: ""

# Speed Perk
SpeedPrice: 100
SpeedExpire: 86400
SpeedLevel: 0
SpeedChance: 100
SpeedDuration: 5
SpeedActivated: "&6&lPERK > &2Speed Perk activated!"
SpeedActivatedActionbar: ""

# Kit Expire Message (Placeholder: %kit_name%)
KitExpireMessage: "&c&lKIT > &7&l%kit_name% Kit &8has expired!"

# Perk Expire Message (Placeholder: %perk_name%)
PerkExpireMessage: "&c&lPERK > &7&l%perk_name% Perk &8has expired!"

# Kick message when a players profile has failed to save
FailedProfileSave: "&cError saving your profile. If this consists please contact &c&lZxoir"

# Error message when selecting same kit
SameKitError: "&c&lERROR > &8You already have that Kit selected!"

# Error when a player leaves spawn without selecting a Kit
NoKitError: "&c&lERROR > &8You must select a Kit!"

# Error when a player tries to access a kit he doesn't have access to
NoKitAccessError: "&c&lERROR > &8You don't have access to that Kit!"

# Error when a player attempts to use the Kit command outside Spawn
KitOutsideSpawnError: "&c&lERROR > &8You can't use that here!"

# Error message when selecting same kit
SamePerkError: "&c&lERROR > &8You already have that Perk selected!"

# Error when a player leaves spawn without selecting a Kit
NoPerkError: "&c&lERROR > &8You must select a Perk!"

# Error when a player tries to access a kit he doesn't have access to
NoPerkAccessError: "&c&lERROR > &8You don't have access to that Perk!"

# Error when a player attempts to use the Kit command outside Spawn
PerkOutsideSpawnError: "&c&lERROR > &8You can't use that here!"

# Message when you are killed (Placeholders: %killer% %killed% %points_removed% %killer_hearts%)
killed_message: "&cYou have been killed by %killer%"
killed_actionbar: "&c-%points_removed%"

# Message when you kill someone (Placeholders: %killer% %killed% %points_gained% %xp_gained%)
kill_message: "&aYou killed %killed%"
kill_actionbar: "&a+%points_gained% &9+%xp_gained%"

# Combatlog messages (Placeholders: %player_hit% %time%)
combat_countdown: true
combat_message: ""
combat_actionbar: "&c&lCOMBATLOG > &8You're in combat for %time% seconds!"
combatlog_kill_message: ""
combatlog_finish_message: "&c&lCOMBATLOG > &aYou're no longer in Combat!"
combat_time: 15

# Message when you level up (Placeholders: %player% %new_level% %old_level%)
levelUp_title: "&a&lYou have leveled up"
levelUp_subtitle: "&9%old_level% &8-> &9%new_level%"
levelUp_broadcast: "&a&l%player% &9has leveled up to &9&l%new_level%&9!"