name: PickMcFFA
version: '${project.version}'
main: me.zxoir.pickmcffa.PickMcFFA
author: Zxoir
depend: [ WorldGuard, WorldEdit, LuckPerms, TAB, HolographicDisplays, PlaceholderAPI, LuckPerms, Votifier, CMI]
commands:
  kit:
    usage: "/kit"
    description: Kit command
  spawnshop:
    usage: "/spawnshop"
    description: Spawnshop command
  pickmc:
    usage: "/pickmc"
    description: Main server command
  stats:
    usage: "/stats"
    description: Stats command
  perk:
    usage: "/perk"
    description: Perk command
    aliases: [ perks ]
  topkills:
    usage: "/topkills"
    description: Shows 10 players with the most kills.
    aliases: [ topkill ]
  topdeaths:
    usage: "/topdeaths"
    description: Shows 10 players with the most deaths.
    aliases: [ topdeath ]
  topkillstreak:
    usage: "/topkillstreak"
    description: Shows 10 players with the most killstreak.
    aliases: [ topks, topkillstreaks ]
  toplevel:
    usage: "/toplevel"
    description: Shows 10 players with the most level.
    aliases: [ toplevels ]
  events:
    usage: "/events"
    description: "Events command"
permissions:
  kit.speed:
    default: op
    description: "Speed Kit"
  kit.tank:
    default: op
    description: "Tank Kit"
  kit.strength:
    default: op
    description: "Strength Kit"
  perk.explosion:
    default: op
    description: "Explosion Perk"
  perk.absorption:
    default: op
    description: "Absorption Perk"
  perk.speed:
    default: op
    description: "Speed Perk"