name: PickMcFFA
version: '${project.version}'
main: me.zxoir.pickmcffa.PickMcFFA
api-version: 1.18
author: Zxoir
depend: [WorldGuard, WorldEdit]
commands:
  kit:
    usage: "/kit"
    description: Kit command
  spawnshop:
    usage: "/spawnshop"
    description: Spawnshop command
  pickmc:
    usage: "/pickmc"
    description: Main server command
permissions:
  kit.speed:
    default: op
    description: "Speed Kit"
  kit.tank:
    default: op
    description: "Tank Kit"
  kit.strength:
    default: op
    description: "Strength Kit"
  perk.explosion:
    default: op
    description: "Explosion Perk"